swagger:
  resourcePackage: com.example.helloworld

database:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://localhost/wizards
  user: site_user
  password: password
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  type: simple
  applicationContextPath: /wizardsbay
  rootPath: /api/
  connector:
    type: http
    port: 8100

# Logging settings.
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO
  # Logger-specific levels.
  loggers:
    edu.neu.cs5500: DEBUG
    org.hibernate.SQL: DEBUG
  appenders:
    - type: console
